\documentclass{ltjsarticle}
\pagestyle{empty}
\title{\LaTeX で3次元プロット}
\author{@kohske}

\begin{document}
\maketitle

% セットアップチャンク
<<include=FALSE>>=
library(knitr)
knit_hooks$set(rgl = hook_rgl)
library(rgl)
@

\texttt{rgl}の図を埋め込むにはフックを指定します。
% フックを指定
<<rgl-sample, rgl=TRUE, fig.align="center", fig.pos="h", out.width="0.8\\linewidth">>=
plot3d(iris[, 1:3], size = 10, col = gray(c(0, 0.2, 0.4))[iris$Species])
@
\end{document}
